### ISSUE TITLE
Controlling color_temp

### ISSUE THREAD

**Issue by waako** [notherealmarco/ha-tradfri-remote#1]
Thanks for this, works well and just what I needed, saves me doing scripts and automations to achieve something similar but much more convoluted.

Currently `brightness_up/down_hold` does nothing (for me at least),  I was toying with the idea before using this as way to change the `color_temp`.

Would that be viable possibility?

**Comment by notherealmarco** [comment]
Brightness hold for now works only for Zigbee devices, you have to install this script in order to make it work: [https://github.com/notherealmarco/ha-zigbee-dimmer](https://github.com/notherealmarco/ha-zigbee-dimmer)
I'm working on an update which brings this functionality also to non-Zigbee devices!
Color temp can be changed with scenes only for now, being able to change CT by holding the buttons might be a future update

**Comment by notherealmarco** [comment]
It should work now! You just need to install this app: [https://github.com/notherealmarco/appdaemon-light-dimmer](https://github.com/notherealmarco/appdaemon-light-dimmer).
Please, let me know if it works correctly

**Comment by waako** [comment]
Thanks, you are right, I hadn't installed the dimmer script.
Didn't think it necessary as I wasn't using `zigbee_names`, I'm controlling HA light groups (which consist of zigbee - Tradfri - light bulbs).

I've not enabled python scripts in my HACS integration as it's marked as deprecated, will test another time as long hold dimming not too important right now.

But thanks for considering the `color_temp` feature, using scenes appears to be acceptable to the rest of the household for now 😄
